file_filter = [".go"]
project_root_filter = ["go.mod"]
module_match = "package_name"
stop_words = ["<end_of_output>"]
code_prompt = """
Your task is to describe the provided code.
First you need to write the package name and collect all the imports.
Then you need to collect and describe all the external data, input sources.
Don't forget to describe cmdline arguments and flags if they present.
You can create any section for that purpose if you need to.
After that you need to describe each code symbol, reducting your output, but trying not to lose the details and original namings.
It is mandatory to prepend the <end_of_output> at the very end of your output.


Example input:
```
package main
import (
	"fmt"
)

func main() {
	fmt.Println("Hello world!")
}
```

Example output:
package: main
imports: fmt

func main():
	- prints "Hello world!"
<end_of_output>

Provided code:
"""
summary_prompt = """
Based on provided input from summary of the project files create a markdown summary of what that project code does.
First write a short summary about provided project code summary.
Always list and specify environment variables, flags, cmdline arguments, files and their paths that can be used for configuration.
Always list and specify the edgecases of how application can be launched.
Try to guess the project name from the filenames if possible and add it as the markdown header of the summary.
Then write summary about every major code part, group it with the markdown subheaders.
Try to explain relations between code entities, try to find unclear places, possibly dead code.		
If unclear places or dead code are not present - don't write anything about their absense.
Try to be clear, concise, and brief.
The main goal is to summarize the logic of the whole project.
It is mandatory to prepend the <end_of_output> at the very end of your output.
"""
package_prompt = """
Based on provided input from the summary of project package files create a markdown summary of what that package code does.
First write a short summary about provided project code summary.
Always list and specify environment variables, flags, cmdline arguments, files and their paths that can be used for configuration.
Always list and specify the edgecases of how application can be launched.
Try to guess package name from the file contents or file paths and add it as the markdown header of the summary.
Write out all file names as a project package structure.
Then write summary about every major code part, group it with the markdown subheaders.
Try to explain relations between code entities, try to find unclear places, possibly dead code.		
If unclear places or dead code are not present - don't write anything about their absense.
Try to be clear, concise, and brief.
The main goal is to summarize the logic of the whole package.
It is mandatory to prepend the <end_of_output> at the very end of your output.
"""
readme_prompt = """
Based on provided input from technical summary of the project create a README.md contents for that project.
Try to guess the project name from filenames or other namings, if present.
Include short project description, possible configuration and/or run instructions.
Always list and specify environment variables, flags, cmdline arguments, files and their paths that can be used for configuration.
Try to be clear, concise, and brief.
It is mandatory to prepend the <end_of_output> at the very end of your output.
"""
